#!/bin/sh /etc/rc.common
#PineAP init.d script.

START=99z

config_load pineap


start() {

    wc -l /etc/pineapple/ssid_file | awk '{print $1}' > /tmp/boot_ssid_count

    config_get_bool status autostart karma 0
    [[ $status -ne 0 ]] && {
      hostapd_cli -i wlan0 karma_enable
    }

    config_get_bool status autostart log_probes 0
    [[ $status -ne 0 ]] && {
      hostapd_cli -i wlan0 karma_log_probes_enable
    }

    config_get_bool status autostart log_associations 0
    [[ $status -ne 0 ]] && {
      hostapd_cli -i wlan0 karma_log_associations_enable
    }

    config_get_bool status autostart pineap 0
    [[ $status -ne 0 ]] && {
      start_pineap &
    }
}

start_pineap() {
    executable="/usr/sbin/pineapple-cli"

    $executable start

    config_get_bool status autostart harvester 0
    [[ $status -ne 0 ]] && {
        $executable harvester start
    }

    config_get_bool status autostart beacon_responses 0
    [[ $status -ne 0 ]] && {
        $executable responder start
    }

    config_get_bool status autostart dogma 0
    [[ $status -ne 0 ]] && {
        $executable dogma start
    }
}

disable() {
    rm /etc/rc.d/*pineap &>/dev/null
}
